# Generated by Django 4.2.28 on 2026-02-05 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('total_equipment', models.IntegerField(default=0)),
                ('avg_flowrate', models.FloatField(default=0.0)),
                ('avg_pressure', models.FloatField(default=0.0)),
                ('avg_temperature', models.FloatField(default=0.0)),
                ('type_distribution', models.TextField(default='{}')),
                ('raw_data', models.TextField(default='[]')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('equipment_type', models.CharField(max_length=100)),
                ('flowrate', models.FloatField(default=0.0)),
                ('pressure', models.FloatField(default=0.0)),
                ('temperature', models.FloatField(default=0.0)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_list', to='api.datasetupload')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
