# Generated by Django 4.2.28 on 2026-02-06 09:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['-recorded_at', 'name']},
        ),
        migrations.AddField(
            model_name='equipment',
            name='recorded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
